name: AutoPost

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: 

# TAMBAHKAN IZIN INI
permissions:
  contents: write

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install requests
      - name: Run Python Script
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: python bot_engine.py
      - name: Commit and Push
        run: |
          git config --local user.email "bot@github.com"
          git config --local user.name "AutoBot"
          git add .
          # Hanya push jika ada perubahan
          git diff --quiet && git diff --staged --quiet || (git commit -m "New Post: $(date)" && git push origin main)
